Add logging documentation
awslabs/mountpoint-s3-csi-driver pull request #206
Opened 2024-06-13 14:44 UTC by monthonk

*Description of changes:*

First pass at logging documentation.

Currently, there is no documentation about how to get the logs for troubleshooting at all. This should provides basic guidance for that.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-13 15:11 UTC, muddyfish commented on docs/LOGGING.md
> +By default, CSI Driver logs are written to pod’s `stderr` and those are captured by Kubernetes and may be retrieved with a corresponding API call:
are written to the _driver_ pod's `stderr`

2024-06-13 15:11 UTC, muddyfish commented on docs/LOGGING.md
> +There are two types of logging you can use for troubleshooting. The first is CSI Driver itself and the other is Mountpoint logs.
The first set logs are from the CSI Driver, and the other are from Mountpoint.

2024-06-13 16:22 UTC, dannycjones reviewed
Nice! Thanks for kicking this off, Monthon.

I have some really nitpicky comments just because this is user documentation.

I'm also wondering how we can make these instructions simpler, but this is a great starting point.

2024-06-13 16:22 UTC, dannycjones commented on docs/LOGGING.md
> +Note down the pod UID and node name. Then connect to the Kubernetes node with the name you got. If you are using EKS with EC2 instances as worker nodes you can find more details about how to connect
```suggestion
Note down the pod UID and node name.

Next, connect to the Kubernetes node with the name discovered in the previous step. If you are using EKS with EC2 instances as worker nodes, you can find more details about how to connect to your nodes in the [AWS documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connect-to-linux-instance.html).
```

2024-06-13 16:22 UTC, dannycjones commented on docs/LOGGING.md
> +    journalctl --unit $UNIT
```suggestion
Once you have a session on the node itself, use the UID noted earlier to find the corresponding Mountpoint logs.

    POD_UID=f1015626-32ed-46e6-9634-c739c3a31312
    PV_NAME=s3-pv
    MOUNT_PID=$(ps -ef | grep "$POD_UID.*$PV_NAME" | grep -v "grep" | awk '{print $2}')
    UNIT=$(systemctl status $MOUNT_PID | grep --only-matching "mount-s3-.*\.service" | tail -1)
    journalctl --unit $UNIT
```

2024-06-13 16:22 UTC, dannycjones commented on docs/LOGGING.md
> +See more details about Mountpoint logging in [Mountpoint documentation](https://github.com/awslabs/mountpoint-s3/blob/main/doc/LOGGING.md).
```suggestion
For more details about Mountpoint logging and the configuration options available, please refer to [Mountpoint's logging documentation](https://github.com/awslabs/mountpoint-s3/blob/main/doc/LOGGING.md).
```

2024-06-14 08:38 UTC, monthonk commented
Thanks both for reviewing. I agree that we should make it simpler, this is only a starting point for the doc.

2024-06-14 10:52 UTC, dannycjones reviewed
Looks good, I'll spin up a cluster to check the steps work on a fresh cluster and then I am happy to merge.

2024-06-14 15:10 UTC, dannycjones requested changes
I tried out the instructions on a cluster, I have a few suggestions

2024-06-14 15:18 UTC, dannycjones commented on docs/LOGGING.md
> +    kubectl logs ${DRIVER_POD} -n kube-system --container s3-plugin
I just updated above to take the first entry (which matches the original `awk`). Not quite as simple now, but hopefully `tail` is more familiar for most than `awk`.

2024-06-25 10:03 UTC, muddyfish approved these changes

2024-06-25 10:49 UTC, dannycjones approved these changes
LGTM, thanks @monthonk

2024-06-25 13:33 UTC, merged