Ensure service account token files are unique per mount
awslabs/mountpoint-s3-csi-driver pull request #236
Opened 2024-08-02 19:19 UTC by unexge

We were using just Volume ID before for service account token files but since same volume can be mounted to multiple Pods, that would cause different Pods to use same tokens. With this PR we're using Pod ID + Volume ID to ensure uniqueness.

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-08-05 09:08 UTC, muddyfish requested changes

2024-08-05 09:08 UTC, muddyfish commented on pkg/driver/credential.go
> +func (c *CredentialProvider) tokenFilename(podID string, volumeID string) string {
Do we also need to include namespaces? Is it plausible that pods in different namespaces could have the same id?

2024-08-05 09:39 UTC, muddyfish commented on pkg/driver/credential.go
> +func (c *CredentialProvider) tokenFilename(podID string, volumeID string) string {
Nevermind, according to [the docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/), UUIDs are unique across a cluster

2024-08-06 08:43 UTC, unexge commented on pkg/driver/credential.go
> +	go func() {
Linters were complaining about the result weren't used and needed to explicitly ignore them to make linters happy

2024-08-06 08:48 UTC, unexge commented on pkg/driver/node.go
> +	targetPathPodIDMapping sync.Map
I don't think Kubernetes would republish events, but we turn on `requiresRepublish` and it should periodically call `NodePublishVolume` and repopulate the map. There might be a time window where our driver dies and `NodeUnpublishVolume` gets called before `NodePublishVolume`, but I think the risk is low to move this into `etcd` or other storage. We also perform a cleanup in `NodeStageVolume` which does not rely on this map, and at worst case if same Pod mounts same Volume, it should perform the cleanup.

2024-08-06 10:06 UTC, unexge commented on pkg/driver/atomicfile.go
> +// Copied from Tailscale, https://github.com/tailscale/tailscale/blob/main/atomicfile/atomicfile.go
Good point, replaced with https://github.com/google/renameio dependency

2024-08-06 12:39 UTC, merged